### ISSUE TITLE
Implement Sessions

### ISSUE THREAD

**Issue by yogeshwar-b** [yogeshwar-b/quizy-be#3]
We need a backend API route/method. Where a host can create a session. This needs to have a browsable route.

something like - localhost/quiz/<mysession>

The player would connect to localhost/quiz/<mysession> which would redirect to localhost/quiz/<mysession>/<customuserid> where they would play the game. Needs research.

**Comment by kool-rokz** [comment]
@yogeshwar-b Please expand upon what is actually needed here.

**Comment by yogeshwar-b** [comment]
Updated description @kool-rokz

**Comment by kool-rokz** [comment]
@yogeshwar-b Sending this your way, for WebSocket based implementation that you tried.

**Comment by yogeshwar-b** [comment]
#12 Implemented Sessions (Now called game rooms)
