### ISSUE TITLE
View questions by session ID

### ISSUE THREAD

**Issue by kool-rokz** [yogeshwar-b/quizy-be#4]
Currently we only expose question retrieval route by question ID. This should much rather be by session ID, where eventually we would switch to handing questions to the client front end automatically.

**Comment by yogeshwar-b** [comment]
Question ID would be needed in the case of a player, who would fetch questions one by one. My initial plan was to get all the question IDs to the front end. Then fetch each question by question ID. This needs to be brainstormed again. How we are planning to deal with players seeing questions one by one. 

@kool-rokz

**Comment by yogeshwar-b** [comment]
This is already implemented.

**Comment by yogeshwar-b** [comment]
This has been already implemented, Refer #12
